POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0M2U5Y2I0ODU4NzdlM2RhNDk0Y2QxYSIsImlhdCI6MTY4MTgyNTA2OX0.Dp97wLOIcG4dCOSjMd2stro_fps3rpNIKshxtMHe7wY

{
  "title": "Test de blooooog",
  "author": "Loan CB",
  "url": "https://google.com",
  "likes": 3
}